// Shop Constants

const ShopActionTypes = {
  FETCH_COLLECTIONS_REQUEST: "FETCH_COLLECTIONS_REQUEST",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAIL: "FETCH_COLLECTIONS_FAIL",
};

export default ShopActionTypes;
